<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Hp_Laptop" failures="1" tests="11" name="PracticeTest" time="0.174" errors="0" timestamp="2025-07-22T00:56:45 PKT">
  <testcase classname="TestNg.Practice_Two" name="ApiLoginCarLoan" time="0.008"/>
  <testcase classname="TestNg.Practice_Two" name="Build" time="0.002"/>
  <testcase classname="TestNg.Practice_One" name="Demo" time="0.021">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNg.Practice_One.Demo(Practice_One.java:13)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="TestNg.Practice_Two" name="MobileLoginCarLoan" time="0.004"/>
  <testcase classname="TestNg.Practice_One" name="SecondDemo" time="0.003"/>
  <testcase classname="TestNg.Practice_Two" name="MobileLoginCarLoan" time="0.001"/>
  <testcase classname="TestNg.Practice_Three" name="Test" time="0.002"/>
  <testcase classname="TestNg.Practice_Two" name="MobileLoginCarLoan" time="0.002"/>
  <testcase classname="TestNg.Practice_Two" name="MobileSignInCarLoan" time="0.001"/>
  <testcase classname="TestNg.Practice_Two" name="MobileSigout" time="0.002"/>
  <testcase classname="TestNg.Practice_Two" name="WebLoginCarLoan" time="0.002"/>
</testsuite> <!-- PracticeTest -->
